spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: postgres
    password: 12345678pP
    driver-class-name: org.postgresql.Driver
  application:
    name: expense-tracker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
server:
  port: 80